### ISSUE TITLE
inventory ui doesnt show without light

### ISSUE THREAD

**Issue by Jomlom** [Into-The-Maze/itm-prototype#13]
idk its weird try it

**Comment by Jomlom** [comment]
inv textures are just too dark and are hard too see if you have a shit coloured monitor (me)

**Comment by L-o-ng** [comment]
Make a 32x32 sprite for 1 inv square then ill add that in

**Comment by L-o-ng** [comment]
push a 5x upscale too just in case

**Comment by Jomlom** [comment]
looks good
